In [2]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [3]:
x.requires_grad_(True)
#等价于 x = torch.arange(4.0, requires_grad=True)
x.grad #默认值是None  这是求导后存储的地方

In [4]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [5]:
y.backward() #手动的反向传播
# 因为反向传播的代价是很大的，所以默认不会自动帮你反向传播，要手动调用
x.grad

tensor([ 0.,  4.,  8., 12.])

In [6]:
x.grad == 4 * x

tensor([True, True, True, True])

In [7]:
#默认情况下，pytorch会累积梯度，所以要记得清除之前的值
x.grad.zero_()
y = x.sum() 
#对自己所有元素求和  求导，显然每一个的梯度都是1
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [15]:
x.grad.zero_()
y = x * x
y.sum().backward()
#等价于y.backward(torch.ones(len(x)))
x.grad

tensor([0., 2., 4., 6.])

In [43]:
x.grad.zero_()
y = x * x
u = y.detach() #将y移出记录的计算图之外
z = u * x

z.sum().backward()
x.grad == u #因此最后u被视为常数

tensor([True, True, True, True])

In [44]:
x.grad.zero_()
y.sum().backward() # 上述操作对y没有影响，是重新计算的

x.grad == 2 * x

tensor([True, True, True, True])

In [49]:
def f(a):
    b = a * 2
    while b.norm() < 1000: # norm 可以理解为向量的长度
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

a = torch.randn(size=(), requires_grad=True)
# size=() 表示一个标量
d = f(a) #对应的也是一个关于a的函数而已
d.backward()

a.grad == d / a

tensor(True)